services:
  PlayerActivityDB:
    image: postgres:latest
    container_name: player_game_scores
    environment:
      POSTGRES_USER: datamanager
      POSTGRES_PASSWORD: password
      POSTGRES_DB: player_activity
    ports:
      - "5432:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - ./seed.sql:/docker-entrypoint-initdb.d/2_seed.sql

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - PlayerActivityDB

volumes:
  postgres_data: